services:
  user-service:
    build: ./user
    ports:
      - "8081:8081"

  course-service:
    build: ./course
    ports:
      - "8083:8083"

  enrollment-service:
    build: ./enrollment
    ports:
      - "8082:8082"
    depends_on:
      - user-service
      - course-service